---
name: release

on:
  pull_request:
    types: [closed]

jobs: 
  build_release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
          
      - name: Install Python Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get upgrade -yqq
          sudo apt-get install -y python3-pip

      - name:  zip python package for release
        run: |
          mkdir erhchecker
          cp src/* erhchecker/
          python3 -m pip install -r files/requirements.txt --target erhchecker --upgrade
          python3 -m zipapp -p "/usr/bin/python3" --compress --output erhchecker.pyz erhchecker 
          tar -cvzf erhchecker_${{matrix.goos}}_${{matrix.goarch}}.gz erhchecker.pyz

      - name: Get version
        id: version
        run: |
          echo "version=$(./erhchecker.pyz -v)" >> $GITHUB_ENV
    
      - name: release
        uses: actions/create-release@v1
        id: release
        with:
          draft: false
          prerelease: false
          release_name: v${{ env.version }}
          tag_name: v${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Artifact for release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: erhchecker_${{matrix.goos}}_${{matrix.goarch}}.tar.gz
          asset_name: erhchecker_${{matrix.goos}}_${{matrix.goarch}}.tar.gz
          asset_content_type: application/gzip
